<a href="https://colab.research.google.com/github/salaam7860/ML-foundations/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# np.random
np.random.random((3,4))

array([[0.55096326, 0.98651537, 0.14736592, 0.48444671],
       [0.22384915, 0.03783915, 0.29789429, 0.69866794],
       [0.7780538 , 0.54085376, 0.23257595, 0.89109147]])

In [ ]:
# np.linspace (lower_range, upper_range, how_many)
np.linspace(-2,5,10)
np.linspace(-4,8,8, dtype=int)

array([-4, -3, -1,  1,  2,  4,  6,  8])

In [ ]:
# np.identity
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# **Array Attributes**

In [3]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) # pehla number ye batata hai kitnay 2D arrays hain thn rows n columns batata hai

In [7]:
# ndim-- no of dimentions
a3.ndim

3

In [8]:
# shape har dimention main rows kitnay hain and columns kitnay hain

a3.shape

(2, 2, 2)

In [9]:
# size -- is array main total kitnay items hain 2x2x2=8
a3.size

8

In [10]:
# item size -- har item memory main kitna size occupy kar raha hai
a1.itemsize

4

In [11]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# **Changing Datatype**

In [12]:
# astype .... memory management kay liye use hota hai
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**


In [17]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)

a1
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Scaler Operations

In [20]:
# arithematic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [19]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

# Vector Operations

In [22]:
# arithematic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# **Array Functions**

In [25]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[35., 40., 66.],
       [13.,  4., 51.],
       [64., 83., 48.]])

In [27]:
# max / min / sum / prod
# 0 -> col and 1 -> row
np.max(a1, axis=1)

array([66., 51., 83.])

In [28]:
# mean / median / std / var
np.mean(a1, axis=0)

array([37.33333333, 42.33333333, 55.        ])

In [29]:
# trigonomatric functions extremly rare to use in data science
np.sin(a1)


array([[-0.42818267,  0.74511316, -0.02655115],
       [ 0.42016704, -0.7568025 ,  0.67022918],
       [ 0.92002604,  0.96836446, -0.76825466]])

In [32]:
# dot product
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
# log and exponents rarly use
np.log(a1)

array([[3.55534806, 3.68887945, 4.18965474],
       [2.56494936, 1.38629436, 3.93182563],
       [4.15888308, 4.41884061, 3.87120101]])

In [38]:
# round / floor / ceil
np.round(np.random.random((2, 3)) * 100)

array([[81., 86., 84.],
       [54., 72., 47.]])

# **Indexing and Slicing**

In [69]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2,2,2)

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
# a2[1][2]
a2[1, 2] # ye bhi aik tareeqa hai

6

In [47]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a3[1, 0, 1]

5

In [49]:
a3[0, 1, 0]

2

In [50]:
a3[0,0,0]

0

# sllicing

In [70]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a1[2:5]

array([2, 3, 4])

In [72]:
# 2D slicing
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a2[0, :]

array([0, 1, 2, 3])

In [74]:
a2[:, 2]

array([ 2,  6, 10])

In [75]:
# [row,column]
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [76]:
 a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [84]:
a2[::2, 1::2] # [::2 means totall rows 2 means alternate, 1::2 = 1 means on every row 1 se aage ::2 means alternate]

array([[ 1,  3],
       [ 9, 11]])

In [86]:
a2[1::, 2::]

array([[ 6,  7],
       [10, 11]])

In [99]:
a2[1, ::3]

array([4, 7])

In [103]:
a2[:2, 1::]

array([[1, 2, 3],
       [5, 6, 7]])

# 3D Arrays Slicing

In [108]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
a3[1, ::2, 0::2]

array([[ 9, 11],
       [15, 17]])

In [118]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
a3[0, 1]

array([3, 4, 5])

In [127]:
a3[1, ::, 1]

array([10, 13, 16])

In [131]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [134]:
 a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

# **Iterating**

In [135]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [136]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
for i in a2:
  for j in i:
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [137]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [143]:
for i in a3:
  for j in i:
    for k in j:
      print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [145]:
# better way
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **Reshaping**

In [146]:
# Reshaping

In [149]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
# Transpose
np.transpose(a2)
a2.T # Better way

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [155]:
# Ravel kitni bhi dimenssion ho ye use 1D kar deta hai good for looping
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# **Stacking** stacking main shape same hona chahiye nahi to kaam nahi kare ga and ye multiple data sources ko join karnay kay liye hai

In [165]:
# Horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12, 24).reshape(3, 4) # (no of rows , no of columns)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [166]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [167]:
# Vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# **Splitting**

In [168]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
# Horizontal splitting
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [176]:
# Vertical splitting
np.vsplit(a4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]